package com.gzeport.casserver.pojo;

import java.util.HashSet;
import java.util.Set;

import org.apache.commons.lang.builder.CompareToBuilder;
import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * AbstractTBaseFuncmodel generated by MyEclipse - Hibernate Tools
 */

public  class FuncModel implements Comparable, java.io.Serializable {

	// Fields

	private String funcId;

	private FuncModel funcmodel;

	private String funcCode;

	private String funcName;

	private String funcSysType;

	private String funcIsmenu;

	private String funcIslast;

	private String funcUrl;

	private String funcResume;

	private String funcUseType;// 使用类型(0,都可使用，1只能是电子口岸)
	
	private String css;
	private String images;
	private boolean disabled;

	private String funcUseType0;

	private String funcUseType1;

	private String funcUseType2;

	private String funcUseType34;

	private Set roleFuncmodels = new HashSet();

	private Set funcmodels = new HashSet();

	// Constructors

	/** default constructor */
	public FuncModel() {

	}

	public FuncModel(String funcId, String funcCode) {
		this.funcId = funcId;
		this.funcCode = funcCode;
	}

	/** full constructor */
	public FuncModel(String funcId, FuncModel funcmodel, String funcCode,
			String funcName, String funcSysType, String funcIsmenu,
			String funcIslast, String funcUrl, String funcResume,
			Set roleFuncmodels, Set funcmodels) {
		this.funcId = funcId;
		this.funcmodel = funcmodel;
		this.funcCode = funcCode;
		this.funcName = funcName;
		this.funcSysType = funcSysType;
		this.funcIsmenu = funcIsmenu;
		this.funcIslast = funcIslast;
		this.funcUrl = funcUrl;
		this.funcResume = funcResume;
		this.roleFuncmodels = roleFuncmodels;
		this.funcmodels = funcmodels;
	}

	// Property accessors

	public FuncModel(String funcId, String funcCode, String funcName,
			String funcIslast, String funcUrl) {
		this.funcId = funcId;
		this.funcCode = funcCode;
		this.funcName = funcName;
		this.funcIslast = funcIslast;
		this.funcUrl = funcUrl;

	}

	public String getFuncCode() {
		return this.funcCode;
	}

	public void setFuncCode(String funcCode) {
		this.funcCode = funcCode;
	}

	public String getFuncName() {
		return this.funcName;
	}

	public void setFuncName(String funcName) {
		this.funcName = funcName;
	}

	public String getFuncSysType() {
		return this.funcSysType;
	}

	public void setFuncSysType(String funcSysType) {
		this.funcSysType = funcSysType;
	}

	public String getFuncIsmenu() {
		return this.funcIsmenu;
	}

	public void setFuncIsmenu(String funcIsmenu) {
		this.funcIsmenu = funcIsmenu;
	}

	public String getFuncIslast() {
		return this.funcIslast;
	}

	public void setFuncIslast(String funcIslast) {
		this.funcIslast = funcIslast;
	}

	public String getFuncUrl() {
		return this.funcUrl;
	}

	public void setFuncUrl(String funcUrl) {
		this.funcUrl = funcUrl;
	}

	public String getFuncResume() {
		return this.funcResume;
	}

	public void setFuncResume(String funcResume) {
		this.funcResume = funcResume;
	}

	public boolean equals(Object obj) {
		if (null == obj)
			return false;
		if (!(obj instanceof FuncModel))
			return false;
		else {
			FuncModel funcmodel = (FuncModel) obj;

			return new EqualsBuilder().appendSuper(super.equals(obj)).append(
					this.funcId, funcmodel.getFuncId()).append(this.funcId,
					funcmodel.getFuncCode()).append(this.funcName,
					funcmodel.getFuncName()).append(this.funcSysType,
					funcmodel.getFuncSysType()).isEquals();
		}
	}

	public int hashCode() {

		return new HashCodeBuilder(-528253723, -475504089).appendSuper(
				super.hashCode()).append(this.funcId).append(this.funcCode)
				.append(this.funcName).append(this.funcSysType).toHashCode();
	}

	public int compareTo(Object obj) {
		int res = -1;
		if (obj != null && this.getClass().isAssignableFrom(obj.getClass())) {
			FuncModel funcmodel = (FuncModel) obj;
			res = new CompareToBuilder().append(this.funcId,
					funcmodel.getFuncId()).append(this.funcCode,
					funcmodel.getFuncCode()).append(this.funcName,
					funcmodel.getFuncName()).append(this.getFuncSysType(),
					funcmodel.getFuncSysType()).toComparison();
		}

		return res;

	}

	public String toString() {
		// return super.toString();
		return ToStringBuilder.reflectionToString(this);
	}

	public FuncModel getFuncmodel() {
		return funcmodel;
	}

	public void setFuncmodel(FuncModel funcmodel) {
		this.funcmodel = funcmodel;
	}

	public Set getFuncmodels() {
		return funcmodels;
	}

	public void setFuncmodels(Set funcmodels) {
		this.funcmodels = funcmodels;
	}

	public Set getRoleFuncmodels() {
		return roleFuncmodels;
	}

	public void setRoleFuncmodels(Set roleFuncmodels) {
		this.roleFuncmodels = roleFuncmodels;
	}

	public String getFuncId() {
		return funcId;
	}

	public void setFuncId(String funcId) {
		this.funcId = funcId;
	}

	public String getCss() {
		return css;
	}

	public void setCss(String css) {
		this.css = css;
	}

	public String getImages() {
		return images;
	}

	public void setImages(String images) {
		this.images = images;
	}

	public String getFuncUseType() {
		return funcUseType;
	}

	public void setFuncUseType(String funcUseType) {
		this.funcUseType = funcUseType;
	}

	public String getFuncUseType0() {
		return funcUseType0;
	}

	public String getFuncUseType1() {
		return funcUseType1;
	}

	public void setFuncUseType1(String funcUseType1) {
		this.funcUseType1 = funcUseType1;
	}

	public String getFuncUseType2() {
		return funcUseType2;
	}

	public void setFuncUseType2(String funcUseType2) {
		this.funcUseType2 = funcUseType2;
	}

	public String getFuncUseType34() {
		return funcUseType34;
	}

	public void setFuncUseType34(String funcUseType34) {
		this.funcUseType34 = funcUseType34;
	}

	public void setFuncUseType0(String funcUseType0) {
		this.funcUseType0 = funcUseType0;
	}


}